<?php 
 /* echo "<pre>";
       print_r($this->getPayment()); 
       die;  */ 
?>
<form id="grid" method="POST" action="<?php echo $this->getUrl('*/*/grid'); ?>">
    <?php echo $this->getBlockHtml('formkey'); ?>

    <div class="entry-edit">
        <?php echo $this->getChild('customer')->setCart($this->getCart())->toHtml(); ?>   
    </div>

    <div class="entry-edit" id="products">
        <?php echo $this->getChildHtml('product'); ?>   
    </div>

    <br>

    <div class="entry-edit">
        <?php echo $this->getChildHtml('item'); ?>   
    </div>
    
    <br>

    <div class="entry-edit">
        <div class="entry-edit-head"><h4>Customer Address</h4></div>
            <fieldset class="a-center bold">
            <span class="nowrap">
            <center>
                <table width="80%" class="table-class">
                    <tr>
                        <td><?php echo $this->getChildHtml('billing'); ?></td>
                        <td width="10%"></td>
                        <td><?php echo $this->getChildHtml('shipping'); ?></td>
                    </tr>
                </table> 
            </center>     
            </span>
        </fieldset>
    </div>

    <br>

    <div class="entry-edit">
        <div class="entry-edit-head"><h4>Payment & Shipping Method</h4></div>
            <fieldset class="a-center bold">
            <span class="nowrap">
            <center>
                <table width="80%" class="table-class">
                    <tr>
                        <td><?php echo $this->getChildHtml('paymentmethod'); ?></td>
                        <td width="10%"></td>
                        <td><?php echo $this->getChildHtml('shippingmethod'); ?></td>
                    </tr>
                </table> 
            </center>     
            </span>
        </fieldset>
    </div>

    <div class="entry-edit">
        <?php echo $this->getChildHtml('total'); ?>   
    </div>
</form>

<script type="text/javascript">
    document.getElementById('products').style.display = "none";

    function showProduct() {
        document.getElementById('products').style.display = "block";
        localStorage.setItem('active',1);
    }

    function redirectUrl(value) {
        form = document.getElementById('grid');
        form.action = value;
        form.submit();
    }
    function validate(url,method = ''){
        tbodys = document.getElementById('shipping').children[0];
        tbodyb = document.getElementById('billing').children[0];
        checkbox = document.getElementById('sameAsBillingcheck').checked;
        if(!checkbox){
            if(method == 's' || method==''){
                for(i=0;i<7;i++){
                    if(tbodys.children[i].children[1].children[0].value == ''){
                        alert("Please Fill All The Field of Shipping Address");
                        return false;
                    }
                }
            }
        }
        if(method == 'b' || method==''){
            for(i=0;i<7;i++){
                if(tbodyb.children[i].children[1].children[0].value == ''){
                    alert("Please Fill All The Field Of Billing Address");
                    return false;
                }
            }
        }
        redirectUrl(url);
    }
</script>