<?php $products = $this->getProducts(); ?>
<div id="products">
    <div id="order-search" class="order-search-items">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <div style="float: right;">
                    <button title="Add Selected Product(s) to Order" type="button" onclick="changeAction('<?php echo $this->getUrl('*/adminhtml_order/addProduct',array('_current' => true)); ?>')" class="scalable add"><span><span><span>Add Selected Product(s) to Order</span></span></span></button>
                </div>
                <h4 class="fieldset-legend head-catalog-product icon-head">Please Select Products to Add</h4>
            </div>
            <div class="fieldset">

                <div id="sales_order_create_search_grid">
                    <div class="grid">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="data" id="sales_order_create_search_grid_table">
                                <col width="60" />
                                <col />
                                <col width="80" />
                                <col width="100" />
                                <col width="55" />
                                <col width="1" />
                                <thead style="background-color: rgb(111, 137, 146);">
                                    <th style="color:white;">ID</th>
                                    <th style="color:white;">Product Name</th>
                                    <th style="color:white;">SKU</th>
                                    <th style="color:white;">Price</th>
                                    <th style="color:white;">Select</th>
                                    <!-- <tr class="headings">
                                            <th><span class="nobr"><a href="#" name="entity_id" title="asc" class="sort-arrow-desc"><span class="sort-title">ID</span></a></span></th>
                                            <th><span class="nobr"><a href="#" name="name" title="asc" class="not-sort"><span class="sort-title">Product Name</span></a></span></th>
                                            <th><span class="nobr"><a href="#" name="sku" title="asc" class="not-sort"><span class="sort-title">SKU</span></a></span></th>
                                            <th><span class="nobr"><a href="#" name="price" title="asc" class="not-sort"><span class="sort-title">Price</span></a></span></th>
                                            <th class="a-center no-link"><span class="nobr">Select</span></th>
                                            <th class=" no-link last"><span class="nobr">Qty To Add</span></th>
                                        </tr> -->
                                    <!-- <tr class="filter">
                                            <th>
                                                <div class="field-100"><input type="text" name="entity_id" id="sales_order_create_search_grid_filter_entity_id" value="" class="input-text no-changes" /></div>
                                            </th>
                                            <th>
                                                <div class="field-100"><input type="text" name="name" id="sales_order_create_search_grid_filter_name" value="" class="input-text no-changes" /></div>
                                            </th>
                                            <th>
                                                <div class="field-100"><input type="text" name="sku" id="sales_order_create_search_grid_filter_sku" value="" class="input-text no-changes" /></div>
                                            </th>
                                            <th>
                                                <div class="range">
                                                    <div class="range-line"><span class="label">From:</span> <input type="text" name="price[from]" id="sales_order_create_search_grid_filter_price_from" value="" class="input-text no-changes" /></div>
                                                    <div class="range-line"><span class="label">To : </span><input type="text" name="price[to]" id="sales_order_create_search_grid_filter_price_to" value="" class="input-text no-changes" /></div>
                                                </div>
                                            </th>
                                            <th class="a-center no-link"><span class="head-massaction"><select name="in_products" id="sales_order_create_search_grid_filter_in_products" class="no-changes">
                                                        <option value="">Any</option>
                                                        <option value="1">Yes</option>
                                                        <option value="0">No</option>
                                                    </select></span></th>
                                            <th class=" no-link last">&nbsp;</th>
                                        </tr> -->
                                </thead>

                                <tbody>
                                    <?php foreach ($products as $key => $product) : ?>
                                        <tr title="#">
                                            <td class=" "><?php echo $product['entity_id']; ?></td>
                                            <td class=" "><?php echo $product['name']; ?></td>
                                            <td class=" "><?php echo $product['sku']; ?></td>
                                            <td class="a-center price a-right "><?php echo $product['price']; ?></td>
                                            <td class="a-center ">
                                                <input type="checkbox" name="products[]" value="<?php echo $product['entity_id']; ?>" class="checkbox" />
                                            </td>
                                            <!-- <td class="a-center last">
                                                    <input type="text" name="qty" value="" class="input-text qty" />
                                                </td> -->
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>