<?php $address = $this->getBillingAddress(); ?>
<div class="entry-edit">

    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend head-billing-address">Billing Address</h4>
        <div class="form-buttons">
                   <button type="button" onclick="redirectUrl('<?php echo $this->getUrl('*/order/saveBillingAddress',array('_current' => true)); ?>')"><span>Save</span></button>
                </div>
     </div>

    <fieldset class="np">

    <div class="order-address" id="order-billing_address_fields">
        <div class="content">
                <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
            <tbody>
<tr>
        <td class="label"><label for="order-billing_address_firstname">First Name <span class="required">*</span></label></td>
    <td class="value">
        <input id="first_name" name="billing[first_name]" value="<?php echo $address->getFirstname(); ?>" class="input-text required-entry" type="text" />
    </tr>
<tr>
        <td class="label"><label for="order-billing_address_lastname">Last Name <span class="required">*</span></label></td>
    <td class="value">
        <input id="last_name" name="billing[last_name]" value="<?php echo $address->getLastname(); ?>" class="input-text required-entry" type="text" />            </td>
    </tr>
<tr>
        <td class="label"><label for="order-billing_address_street0">Street Address <span class="required">*</span></label></td>
    <td class="value">
        <div class="multi-input"><input id="street" name="billing[street]" value="<?php echo $address->getStreet(); ?>" class="input-text required-entry" type="text" />
</div>         </td>
    </tr>
<tr>
        <td class="label"><label for="order-billing_address_city">City <span class="required">*</span></label></td>
    <td class="value">
        <input id="city" name="billing[city]" value="<?php echo $address->getCity(); ?>" class="input-text required-entry" type="text" />            </td>
    </tr>
<tr>
        <td class="label"><label for="order-billing_address_postcode">Zip/Postal Code <span class="required">*</span></label></td>
    <td class="value">
        <input id="postcode" name="billing[postcode]" value="<?php echo $address->getPostcode(); ?>" class="input-text required-entry" type="text" />            </td>
    </tr>
<tr>
        <td class="label"><label for="order-billing_address_telephone">Telephone <span class="required">*</span></label></td>
    <td class="value">
       <input id="telephone" name="billing[telephone]" value="<?php echo $address->getTelephone(); ?>" class="input-text required-entry" type="text" />            </td>
    </tr>

            </tbody>
        </table>
            </div>
            </div>
        <div class="order-save-in-address-book">
                        <input type="checkbox" name="billingSaveAddressBook">
                        <label for="saveToAddress">Save in address book</label>
                    </div>
    </div>
        <div style="display:none;" id="address-billing-overlay" class="overlay"><span>Shipping address selection is not applicable</span></div>
    
    </fieldset>
</div>