<?php $address = $this->getBillingAddress(); ?>
<div class="entry-edit">

    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend head-billing-address">Billing Address</h4>
        <div class="form-buttons">
                   <button type="button" onclick="redirectUrl('<?php echo $this->getUrl('*/order/saveBillingAddress',array('_current' => true)); ?>')"><span>Save</span></button>
                </div>
     </div>

    <fieldset class="np">

    <div class="order-address" id="order-billing_address_fields">
        <div class="content">
                <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
            <tbody>
<tr>
        <td class="label"><label for="order-billing_address_firstname">First Name <span class="required">*</span></label></td>
    <td class="value">
        <input id="first_name" name="billing[first_name]" value="<?php echo $address->getFirstname(); ?>" class="input-text required-entry" type="text" />
    </tr>
<tr>
        <td class="label"><label for="order-billing_address_lastname">Last Name <span class="required">*</span></label></td>
    <td class="value">
        <input id="last_name" name="billing[last_name]" value="<?php echo $address->getLastname(); ?>" class="input-text required-entry" type="text" />            </td>
    </tr>
<tr>
        <td class="label"><label for="order-billing_address_street0">Street Address <span class="required">*</span></label></td>
    <td class="value">
        <input type="text" name="billing[address]" id="address" value="<?php if($cartBillingAddress->street){echo $cartBillingAddress->street;}if($cartBillingAddress->address){echo $cartBillingAddress->address;}?>"
                                              placeholder="Address" class="form-control">
</div>         </td>
    </tr>
<tr>
        <td class="label"><label for="order-billing_address_city">City <span class="required">*</span></label></td>
    <td class="value">
        <input type=" text" name="billing[city]" id="lastname" value="<?php echo $cartBillingAddress->city?>"
                                              placeholder="City" class="form-control">           </td>
    </tr>
<tr>
        <td class="label"><label for="order-billing_address_postcode">Zip/Postal Code <span class="required">*</span></label></td>
    <td class="value">
       <input type="text" name="billing[zipcode]" id="zipcode" value="<?php if($cartBillingAddress->zipcode){echo $cartBillingAddress->zipcode;}if($cartBillingAddress->postcode){echo $cartBillingAddress->postcode;}?>"
                                              placeholder="Zipcode" class="form-control"></td>
    </tr>
<tr>
        <td class="label"><label for="order-billing_address_telephone">Telephone <span class="required">*</span></label></td>
    <td class="value">
        <input type="number" name="billing[phone]" id="phone" value="<?php if($cartBillingAddress->phone){echo $cartBillingAddress->phone;}if($cartBillingAddress->telephone){echo $cartBillingAddress->telephone;} ?>"
                                              placeholder="Country" class="form-control">            </td>
    </tr>

            </tbody>
        </table>
            </div>
            </div>
        <div class="order-save-in-address-book">
                        <input type="checkbox" name="billingSaveAddressBook">
                        <label for="saveToAddress">Save in address book</label>
                    </div>
    </div>
        <div style="display:none;" id="address-billing-overlay" class="overlay"><span>Shipping address selection is not applicable</span></div>
    
    </fieldset>
</div>