<?php 

$customer = $this->getCart()->getCustomer();

?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head fieldset-legend head-account">Account Information</h4>
        </div>
        <div id="customer_account_fieds">
            <div class="fieldset " id="main">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
            <tbody>
        <tr>
            <td class="label"><label for="name">Name</label></td>
        <td class="value">
            <?php echo $customer->getName(); ?>
        </td>
        </tr>
        <tr>
            <td class="label"><label for="email">Email</label></td>
        <td class="value">
             <?php echo $customer->getEmail(); ?>
        </td>

        </tr>
                </tbody>
            </table>
                </div>
            </div>
        </div>
        
    </div>