<?php 

?>

<?php echo $this->getBlockHtml('formkey');?>
 	<div class="entry-edit">
        <?php echo $this->getChild('customer')->setCart($this->getCart())->toHtml(); ?>   
    </div>
    <div class="entry-edit">
        <?php echo $this->getChildHtml('product'); ?>   
    </div>

    <br>

    <div class="entry-edit">
        <?php echo $this->getChildHtml('item'); ?>   
    </div>
    
    <br>

    <div class="entry-edit">
        <div class="entry-edit-head"><h4>Customer Address</h4></div>
            <fieldset class="a-center bold">
            <span class="nowrap">
            <center>
                <table width="80%" class="table-class">
                    <tr>
                        <td><?php echo $this->getChildHtml('billing'); ?></td>
                        <td width="10%"></td>
                        <td><?php echo $this->getChildHtml('shipping'); ?></td>
                    </tr>
                </table> 
            </center>     
            </span>
        </fieldset>
    </div>

    <br>

    <div class="entry-edit">
        <div class="entry-edit-head"><h4>Payment & Shipping Method</h4></div>
            <fieldset class="a-center bold">
            <span class="nowrap">
            <center>
                <table width="80%" class="table-class">
                    <tr>
                        <td><?php echo $this->getChildHtml('paymentmethod'); ?></td>
                        <td width="10%"></td>
                        <td><?php echo $this->getChildHtml('shippingmethod'); ?></td>
                    </tr>
                </table> 
            </center>     
            </span>
        </fieldset>
    </div>

    <div class="entry-edit">
        <?php echo $this->getChildHtml('total'); ?>   
    </div>

