<?php $paymentMethod = $this->getPaymentMethod();
$paymentCode = $this->getCart()->getPaymentMethodCode();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"></div>
        <h4 class="fieldset-legend head-payment-method icon-head">Payment Method</h4>
        <div class="form-buttons">
                    <button id="submit_order_top_button" type="button" onclick="redirectUrl('grid','<?php echo $this->getPaymentMethodUrl(); ?>');" class="scalable save">
                        <span><span><span>Save</span></span></span>
                    </button>
                </div>
    </div>
    <div class="fieldset">
        <div id="order-billing_method_form">
    <dl class="payment-methods">
                <dt>
                    <?php if ($paymentMethod) : ?>
                                <?php foreach ($paymentMethod as $key => $value) : ?>
                                    <input type="radio" value="<?php echo $key ?>" <?php if($key == $paymentCode): ?> checked <?php endif; ?>  name="paymentMethod">
                                <?php echo $value->getTitle(); ?><br>
                                <?php endforeach; ?>
                            <?php else : ?>
                                <label for="p_method_free">No Payment Available</label>
                            <?php endif; ?>
        </dt>
        <dd>
                    </dd>
        </dl>
</div>

    </div>
</div>