<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"></div>
        <h4 class="fieldset-legend head-payment-method icon-head">Payment Method</h4>
    </div>
    <div class="fieldset">
        <div id="order-billing_method_form">
    <dl class="payment-methods">
                <dt>
                    <span class="no-display"><input id="p_method_free" value="free" type="radio" name="payment[method]" checked="checked"></span>
        
            <label for="p_method_free">No Payment Information Required</label>
        </dt>
        <dd>
                    </dd>
        </dl>
</div>

    </div>
</div>