<?php $address = $this->getShippingAddress(); ?>
<div class="entry-edit" style="position: relative;">

    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend head-shipping-address">Shipping Address</h4>
        <div class="form-buttons">
                <button id="submit_order_top_button" type="button" onclick="return validate('<?php echo $this->getShippingMethodUrl() ?>','s');" class="scalable save">
                    <span><span><span>Save</span></span></span>
                </button>
            </div>
     </div>

    <fieldset class="np">
    <div class="order-address" id="order-shipping_address_fields">
        <div class="content">
                <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
            <tbody>
<tr>
        <td class="label"><label for="order-shipping_address_firstname">First Name <span class="required">*</span></label></td>
    <td class="value">
                                        <input id="first_name" name="shipping[first_name]" value="<?php echo $address->getFirstname(); ?>" class="input-text required-entry" type="text" />
                                    </td>
<tr>
        <td class="label"><label for="order-shipping_address_lastname">Last Name <span class="required">*</span></label></td>
    <td class="value">
        <input id="last_name" name="shipping[last_name]" value="<?php echo $address->getLastname(); ?>" class="input-text required-entry" type="text" />
    </tr>
<tr>
        <td class="label"><label for="order-shipping_address_street0">Street Address <span class="required">*</span></label></td>
    <td class="value">
        <div class="multi-input"><input id="street" name="shipping[street]" value="<?php echo $address->getStreet(); ?>" class="input-text required-entry" type="text" />
</div>          </td>
    </tr>
<tr>
        <td class="label"><label for="order-shipping_address_city">City <span class="required">*</span></label></td>
    <td class="value">
        <input id="city" name="shipping[city]" value="<?php echo $address->getCity(); ?>" class="input-text required-entry" type="text" />            </td>
    </tr>
<tr>
        <td class="label"><label for="order-shipping_address_postcode">Zip/Postal Code <span class="required">*</span></label></td>
    <td class="value">
        <input id="postcode" name="shipping[postcode]" value="<?php echo $address->getPostcode(); ?>" class="input-text required-entry" type="text" />            </td>
    </tr>
<tr>
        <td class="label"><label for="order-shipping_address_telephone">Telephone <span class="required">*</span></label></td>
    <td class="value">
        <input id="telephone" name="shipping[telephone]" value="<?php echo $address->getTelephone(); ?>" class="input-text required-entry" type="text" />            </td>
    </tr>
            </tbody>
        </table>
            </div>
            </div>
    </div>
    </fieldset>
</div>