<div class="entry-edit">
            <div class="entry-edit-head"><h4>Order Totals</h4></div>
            <div id="order-totals" class="order-totals"><table cellspacing="0" cellpadding="8" width="100%">
    <tbody>
        <tr>
    <td style="" class="a-right" colspan="1">
        Subtotal    </td>
    <td style="" class="a-right">
        <span class="price">$0.00</span>    </td>
</tr>
        <tr>
    <td style="" class="a-right" colspan="1">
        <strong>Grand Total</strong>
    </td>
    <td style="" class="a-right">
        <strong><span class="price">$0.00</span></strong>
    </td>
</tr>
    </tbody>
</table>
<div class="divider"></div>
<div class="order-totals-bottom">
    <p>
        <label for="notify_customer" class="normal">Append Comments</label>
        <input type="checkbox" id="notify_customer" name="order[comment][customer_note_notify]" value="1">
    </p>
        <p>
        <label for="send_confirmation" class="normal">Email Order Confirmation</label>
        <input type="checkbox" id="send_confirmation" name="order[send_confirmation]" value="1" checked="checked">
    </p>
        <p><button id="id_ee577e2e50d6bab94846110ecb1208aa" title="Submit Order" type="button" class="scalable save" onclick="order.submit()" style=""><span><span><span>Submit Order</span></span></span></button></p>
</div>


</div>
        </div>